### ISSUE TITLE
Update the guide for outdated instructions

### ISSUE THREAD

**Issue by shin19991207** [OpenLiberty/guide-cloud-aws#223]
- Remove the section for 'IAM Authenticator' in the 'Additional prerequisites' section because it is now integrated into AWS CLI V2 and there's no need to install it individually anymore.
- In the 'Configuring the AWS CLI' section, mention about the minimum AWS permissions policies needed to run the guide.
- Include `--platform linux/amd64` for docker build commands.

**Comment by gkwan-ibm** [comment]
close
- the guide was updated
