### ISSUE TITLE
Post-Publishing

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-cloud-aws#34]
Post-Publishing Tests (Danny)
- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [x] Clone repo from master and do end to end

Other post-publishing tasks (to be done by the Admin Team) (Eveline)
- [x] Add description for the repo with link to guide's published website
- [x] Ensure automated tests for PR and Daily builds using Travis, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
- [x] Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#subscribing-static-guides-repositories-to-a-slack-channel)
- [x] Add the new guide's repo to the `OpenLiberty/guides-common` ZenHub board
- [x] (Optional) Send announcement to slack channel(s)
- [x] Consider SEO title and description for the guides
- [x] Enable `master` and `qa` branches lock down

**Comment by evelinec** [comment]
Completed.
