### ISSUE TITLE
Dev Content Review

### ISSUE THREAD

**Issue by ankitagrawa** [OpenLiberty/guide-cloud-aws#75]
**Additional prerequisites**

- IAM Authenticator:
to install the AWS IAM Authenticator on your `platform`..

I believe `platform` should be replaced with `laptop` or `local machine` 
Also keep one dot at the end of the sentence 

- eksctl
CLI should be Command Line Interface (CLI)

- AWS CLI: ### You will need to use the AWS Command Line Interface (CLI). To install the AWS CLI, Python must be installed. See the Downloading Python documentation to download the latest version of Python.
After Python is installed, install the AWS CLI by following the instructions in the official Installing the AWS CLI documentation.###
I guess "After Python is installed, install the AWS CLI..." shouldn't be on the different line. It should be right after "...version of Python"

**Comment by ankitagrawa** [comment]
**Creating a Kubernetes cluster on EKS**
"After you are done filling out this information, the settings are stored in the default profile. Anytime that you run an AWS CLI command without specifying a profile, the default profile is used."

remove that

**Comment by ankitagrawa** [comment]
**Building and containerizing the microservices**

Next, run the docker build commands to build container images for your application:

add 'The' before container.

**Comment by ankitagrawa** [comment]
**Testing microservices that are running on AWS EKS**

How to run the test cases. No instructions on that. Give some info on how to run them or they run automatically. What would be a sample expected output.

**Comment by DannyS03** [comment]
> **Additional prerequisites**
> 
>     * IAM Authenticator:
>       to install the AWS IAM Authenticator on your `platform`..
> 
> 
> I believe `platform` should be replaced with `laptop` or `local machine`
> Also keep one dot at the end of the sentence
> 
>     * eksctl
>       CLI should be Command Line Interface (CLI)
> 
>     * AWS CLI: ### You will need to use the AWS Command Line Interface (CLI). To install the AWS CLI, Python must be installed. See the Downloading Python documentation to download the latest version of Python.
>       After Python is installed, install the AWS CLI by following the instructions in the official Installing the AWS CLI documentation.###
>       I guess "After Python is installed, install the AWS CLI..." shouldn't be on the different line. It should be right after "...version of Python"



> **Additional prerequisites**
> 
>     * IAM Authenticator:
>       to install the AWS IAM Authenticator on your `platform`..
> 
> 
> I believe `platform` should be replaced with `laptop` or `local machine`
> Also keep one dot at the end of the sentence
> 
>     * eksctl
>       CLI should be Command Line Interface (CLI)
> 
>     * AWS CLI: ### You will need to use the AWS Command Line Interface (CLI). To install the AWS CLI, Python must be installed. See the Downloading Python documentation to download the latest version of Python.
>       After Python is installed, install the AWS CLI by following the instructions in the official Installing the AWS CLI documentation.###
>       I guess "After Python is installed, install the AWS CLI..." shouldn't be on the different line. It should be right after "...version of Python"

- `platform` sounds more versatile.
- other two points addressed.

**Comment by DannyS03** [comment]
> **Creating a Kubernetes cluster on EKS**
> "After you are done filling out this information, the settings are stored in the default profile. Anytime that you run an AWS CLI command without specifying a profile, the default profile is used."
> 
> remove that

- wouldn't it be fine to include information about the profile? 
- information is also relevant to the section of `Creating a Kubernetes cluster on EKS`.

**Comment by DannyS03** [comment]
> **Building and containerizing the microservices**
> 
> Next, run the docker build commands to build container images for your application:
> 
> add 'The' before container.
> 
> **Pushing the images to a container registry**
> The registry that you use is called Amazon Elastic Container Registry (ECR).
> should be "that you would be using is ...."

- addressed both. 
- rather than `that you would be using is ....`, updated too `The registry that you are using is called Amazon Elastic Container Registry (ECR).`

**Comment by DannyS03** [comment]
> **Testing microservices that are running on AWS EKS**
> 
> How to run the test cases. No instructions on that. Give some info on how to run them or they run automatically. What would be a sample expected output.

- information is included in README.adoc, though was not showing up oh dev site due to syntax error. 
- addressed.

**Comment by ankitagrawa** [comment]
LGTM
