### ISSUE TITLE
Peer Review - Mac

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/guide-cloud-aws#77]
### Pushing the images to a container registry
- [x] `get-login-password` command doesn't work
    - should be `aws ecr get-login-password`
        - this doesn't return:
            > docker login -u AWS -p [password_string] https://[aws_account_id].dkr.ecr.us-east-2.amazonaws.com
        - it returns just the [password_string]
        - [x] put the docker login thing above as a command box and tell the users to replace [password_string]. Tell them how to find [aws_account_id] since the command doesn't give that (`aws sts get-caller-identity --output text --query 'Account'`)

### Making requests to the microservices

- [x] Move this section later to right before the sentence `Then, curl or visit the following URLs to access your microservices, substituting the appropriate hostname:`
    > Take note of the `EXTERNAL-IP` in the output of the following command. It is the
    > hostname you will later substitute into `[hostname]`:
    > [role=command]
    > ```
    > kubectl get nodes -o wide
    > ```
- [x] `http://[hostname]:32000/inventory/systems/` doesn't work

### Testing microservices that are running on AWS EKS
- [x] IT tests don't work
- [x] Don't refer the openshift dev mode and azure dev mode conversion since they do it differently than aws (has two different inventory.ip and system.ip. Compared to aws which only uses one ip, which it had before: `cluster.ip`)
     - refer to the google cloud guide, which has similar situations
    - [x] change this section back to the original properties (with cluster.ip, etc.)
        ![image](https://user-images.githubusercontent.com/46586499/76889368-d8648380-685b-11ea-97e2-2bd1a8bd7bf2.png)
    - [x] change the pom.xml files and server.xml and IT files to fit aws's cluster.ip and node ports

### Diff between start and finish

- [x] difference for failsafe plugin between `inventory/pom.xml` in `start` and `finish`
- [x] extra spacing difference between `inventory/src/main/liberty/config/server.xml` in start` and `finish`
- [x] extra spacing difference between `finish/pom.xml` and `start/pom.xml`
- [x] diff between `finish/system/pom.xml` and `start/system/pom.xml` for spacing and properties
- [x] diff between spacing in `finish` and `start` for `system/src/main/liberty/config/server.xml`

### Other
- [x] `artifactId` in `pom.xml` should not be `kube-demo`. It should be the guide name, `guide-cloud-aws`
- [x] remove `:page-search-keywords:` from readme, now outdated
- [x] remove extra period in SEO description in readme
- [x] if you're combining the `failsafe:integration-test` goal and `failsafe:verify` goal to be part of `mvn verify` in the pom (like you are in `start/pom.xml`), then in the readme in the testing section, change `mvn failsafe:integration-test -Dcluster.ip=[hostname]` back to 
`mvn verify -Dcluster.ip=[hostname]`.
    - or don't combine those goals in the pom. 
And keep `mvn failsafe:integration-test -Dcluster.ip=[hostname]` in the readme
- [x] travisTest.sh
    - [x] remove `-Ddockerfile.skip=true`
    - [x] if not combining the failsafe goals, change
        ```
        mvn verify -Ddockerfile.skip=true -Dcluster.ip=`minikube ip`
        ```
        to
        ```
        mvn failsafe:integration-test -Dcluster.ip=`minikube ip`
        mvn verify
        ```
- [x] travisTest.sh is failing

**Comment by NimG98** [comment]
- [ ] still some differences in spacing between some files in `start` and `finish`

**Comment by DannyS03** [comment]
>     * [ ]  still some differences in spacing between some files in `start` and `finish`

Which files?

**Comment by NimG98** [comment]
Run `diff -rq finish start` to see which files

**Comment by DannyS03** [comment]
>     * [x]  still some differences in spacing between some files in `start` and `finish`

addressed.

**Comment by NimG98** [comment]
- [ ] licensing for all IT files should be `2018, 2020`

**Comment by DannyS03** [comment]
>     * [x]  licensing for all IT files should be `2018, 2020`

addressed.
