### ISSUE TITLE
Peer Review - Windows

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-cloud-aws#78]
Peer Review: review to be done by a peer member. 

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [ ] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
    - [x] Define test coverage and review with team (including guide contributor, if available)
    - [x] Define detail test cases 
    - [x] Consider corner cases targeting the specific guide
    - [x] Consider different platform tests, ie, Mac, Windows, Linux
    - [x] Consider corner cases UI tests
    - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [x] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases 

-----

## Configuring the AWS CLI 
- Move the `After the AWS CLI is installed, it must be configured by running the AWS configure command.` line to the end of the paragraph, right before the code block, for better guide flow and readability.
- I don't understand what I'm supposed to provide for the things that the `aws configure` command prompts for. Do I leave them blank? The guide needs to be more specific.
- After configuring aws, maybe ask the user to run `aws configure list` to verify their values.

## Pushing the images to a container registry
- The command `aws sts get-caller-identity --output text --query 'Account'` needs to have double quotes, not single -> `"Account"`
- The following command: `docker login -u AWS -p [password_string] https://[aws_account_id].dkr.ecr.us-east-2.amazonaws.com` has the region hard coded `us-east-2`, even though the guide previously prompted users to select the region best fit for them. The region should follow the `password_string` example and be a variable. 
- Ensure you update the output of the `aws ecr create-repository ... ` commands to match the above region variable.

## Making requests to the microservices
- the `aws ec2 describe-security-groups ...` command should show the example response output

## Deploying new version of system microservice
- Why are we asking the users to repackage if we haven't made any changes to the source code?

**Comment by DannyS03** [comment]
- all addressed except
  - last comment on asking the users to repackage. In the beginning of the section the guide suggests that user can change their microservices; meaning they would need to repackage (and despite the conversion to dev mode the guide will not use the development feature). Seems like it was the initial attempt when the guide was first created, though we can bring it up when there is another dev content review.

**Comment by DannyS03** [comment]
- all addressed except
  - last comment on asking the users to repackage. In the beginning of the section the guide suggests that user can change their microservices; meaning they would need to repackage (and despite the conversion to dev mode the guide will not use the development feature). Seems like it was the initial attempt when the guide was first created, though we can bring it up when there is another dev content review.

- for info regarding the `aws configure` command prompting for: info is already included i
 the guide, though it is after the command. I rearranged the content to make it flow better.

**Comment by MaiHameed** [comment]
LGTM
